jwt:
  secret: T0yiFsvQtrzh50zv4tyWUMRdtIQF3QtY
  header: Authorization
  issuer: JangSeongBin
  access-token-expire-minute: 10
  refresh-token-expire-minute: 120

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
